[package]
name = "peroxide"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"

[dependencies]
anyhow = "1.0.61"
ez_input = { git = "https://github.com/R-ARM/ez_input.git", branch = "main" }
crossterm = "0.25.0"
efivar = "0.2.1"
uefi = { version = "0.16.0", features = [ "exts" ] }
regex = "1.6.0"
uuid = "1.1.2"
nix = { version = "0.25.0", features = [ "reboot", "fs" ] }
